[project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
name = "dash-pydantic-form"

[environments]
default = {features = ["form", "pandas", "dev"], solve-group = "default"}

[dependencies]
python = ">=3.10"
pydantic = ">=2,<3"

[pypi-dependencies]
"dash-pydantic-form" = { path = "packages/dash-pydantic-form", editable = true }
"dash-pydantic-utils" = { path = "packages/dash-pydantic-utils", editable = true }

[feature.form.dependencies]
dash = ">=2,<3"
dash-mantine-components = ">=0.14.5,<0.16"
dash-iconify = "*"
dash-ag-grid = ">=31"
fsspec = "*"

[feature.pandas.dependencies]
numpy = "*"
pandas = "*"

[feature.dev.dependencies]
python = ">=3.10,<3.11"
pre-commit = "*"
pytest = "*"

[feature.dev.pypi-dependencies]
dash = {extras = ["testing"], version = ">=2,<3"}
